# docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
version: '3'

services:
  mattermost:
    image: mattermost/mattermost-preview
    container_name: mattermost-preview
    ports:
      - "8065:8065"
    depends_on:
      - db
