services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./storage/dms/mail-data/:/var/mail/
      - ./storage/dms/mail-state/:/var/mail-state/
      - ./storage/dms/mail-logs/:/var/log/mail/
      - ./storage/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

  roundcubemail:
    image: roundcube/roundcubemail:latest-fpm
    container_name: roundcubemail
    # restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 9000:9000
    volumes:
      - ./storage/www:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as pgsql container name
      - ROUNDCUBEMAIL_DB_NAME=roundcube # same as pgsql POSTGRES_DB env name
      - ROUNDCUBEMAIL_DB_USER=roundcube # same as pgsql POSTGRES_USER env name
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube # same as pgsql POSTGRES_PASSWORD env name
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.example.org
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.example.org

  roundcubedb:
    image: postgres:latest
    container_name: roundcubedb
    # restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=roundcube

  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    # restart: unless-stopped
    ports:
      - 9009:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - roundcubemail
    links:
      - roundcubemail
    volumes:
      - ./storage/www:/var/www/html
      - ./storage/nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost  # set your local domain or your live domain
      - NGINX_PHP_CGI=roundcubemail:9000  # same as roundcubemail container name

### Optional: add a full mail server stack to use with Roundcube like https://hub.docker.com/r/tvial/docker-mailserver
#   mailserver:
#     image: tvial/docker-mailserver:latest
#     hostname: mail.example.org
#     ...  # for more options see https://github.com/tomav/docker-mailserver#examples