services:
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - "8389:389"
      - "8636:636"
    volumes:
      - ~/ldap/backup:/data/backup
      - ~/ldap/data:/var/lib/openldap
      - ~/ldap/config:/etc/openldap/slapd.d
      - ~/ldap/certs:/assets/slapd/certs
    command: [--copy-service,  --loglevel, debug]
  ldap-ui:
        image: dnknth/ldap-ui
        ports:
            - 127.0.0.1:5000:5000
        links:
          - openldap
        environment:
            LDAP_URL: "${LDAP_URL:-ldap://openldap/}"
            USE_TLS: ${USE_TLS:-}
            INSECURE_TLS: ${INSECURE_TLS:-}
            BASE_DN: "${BASE_DN:-dc=example,dc=org}"
            BIND_DN: "${BIND_DN:-cn=admin,dc=example,dc=org}"
            BIND_PASSWORD: "${BIND_PASSWORD:-admin}"
        restart: unless-stopped
        healthcheck:
            test: "wget -q -O /dev/null http://localhost:5000"
            interval: 30s
            retries: 2
            timeout: 2s
