services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    # ports:
    #   - 8000:8000
    #   - 9443:9443
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/portainer:/data
    networks:
      - web_service

networks:
  web_service:
    external: true
